INSERT INTO nexti.dbo.FLEX_UNIDADE
SELECT 
NOMFIL AS NOME,
CODFIL AS CODIGO,
CODFIL AS CODIGO_FILIAL,
CNPJ AS CNPJ,
0 AS TIPO,
0 AS SITUACAO,
'' AS OBSERVACAO,
0 AS ID,
IDEXTERNO AS IDEXTERNO
FROM nexti.dbo.FLEX_EMPRESA
WHERE NOT EXISTS(
        SELECT 1 FROM nexti.dbo.FLEX_UNIDADE
        WHERE nexti.dbo.FLEX_UNIDADE.IDEXTERNO = nexti.dbo.FLEX_EMPRESA.IDEXTERNO
    )