INSERT INTO nexti.dbo.FLEX_EMPRESA
SELECT
1 AS NUMEMP,
M0_CODFIL AS CODFIL,
M0_NOME AS RAZSOC,
M0_NOMECOM AS NOMFIL,
M0_CGC AS CNPJ,
0 AS TIPO,
0 AS SITUACAO,
'' AS OBSERVACAO,
0 AS ID,
R_E_C_N_O_ AS IDEXTERNO
FROM ALIANCA.dbo.SYS_COMPANY
WHERE NOT EXISTS(
		SELECT 1 FROM nexti.dbo.FLEX_EMPRESA
		WHERE IDEXTERNO = ALIANCA.dbo.SYS_COMPANY.R_E_C_N_O_
	)