UPDATE Nexti.dbo.FLEX_COLABORADOR
SET Nexti.dbo.FLEX_COLABORADOR.DATADEMISSAO = LTRIM(RTRIM(SRA010.RA_DEMISSA))
FROM Nexti.dbo.FLEX_COLABORADOR
JOIN TOTVS_12.dbo.SRA010 SRA010
	ON SRA010.R_E_C_N_O_ = Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO
AND Nexti.dbo.FLEX_COLABORADOR.ID > 0
AND LTRIM(RTRIM(Nexti.dbo.FLEX_COLABORADOR.DATADEMISSAO)) <> LTRIM(RTRIM(SRA010.RA_DEMISSA)) collate database_default
