UPDATE nexti.dbo.FLEX_COLABORADOR
SET nexti.dbo.FLEX_COLABORADOR.DATADEMISSAO = LTRIM(RTRIM(SRA010.RA_DEMISSA))
FROM nexti.dbo.FLEX_COLABORADOR
JOIN ALIANCA.dbo.SRA010 SRA010
	ON SRA010.R_E_C_N_O_ = nexti.dbo.FLEX_COLABORADOR.IDEXTERNO
AND nexti.dbo.FLEX_COLABORADOR.ID > 0
AND LTRIM(RTRIM(nexti.dbo.FLEX_COLABORADOR.DATADEMISSAO)) <> LTRIM(RTRIM(SRA010.RA_DEMISSA)) collate database_default
