UPDATE Nexti.dbo.FLEX_COLABORADOR
SET
Nexti.dbo.FLEX_COLABORADOR.CEP = SRA010.RA_CEP,
Nexti.dbo.FLEX_COLABORADOR.NOMFUN = LTRIM(RTRIM(SRA010.RA_NOME)),
Nexti.dbo.FLEX_COLABORADOR.ENDERECO = RTRIM(RA_ENDEREC),
Nexti.dbo.FLEX_COLABORADOR.COMPLEMENTO= RTRIM(RA_COMPLEM),
Nexti.dbo.FLEX_COLABORADOR.NUMERO = RTRIM(RA_NUMENDE),
Nexti.dbo.FLEX_COLABORADOR.BAIRRO = RTRIM(RA_BAIRRO),
Nexti.dbo.FLEX_COLABORADOR.CIDADE = (RA_MUNICIP),
Nexti.dbo.FLEX_COLABORADOR.ESTADO = RTRIM(RA_ESTADO),
Nexti.dbo.FLEX_COLABORADOR.DATADMISSAO = RA_ADMISSA,
Nexti.dbo.FLEX_COLABORADOR.DATANASCIMENTO = SRA010.RA_NASC,
Nexti.dbo.FLEX_COLABORADOR.CARGO = Nexti.dbo.FLEX_CARGO.IDEXTERNO,
Nexti.dbo.FLEX_COLABORADOR.CPF = RTRIM(SRA010.RA_CIC),
Nexti.dbo.FLEX_COLABORADOR.RG = RTRIM(SRA010.RA_RG),
Nexti.dbo.FLEX_COLABORADOR.PIS = RTRIM(SRA010.RA_PIS),
Nexti.dbo.FLEX_COLABORADOR.GENERO = SRA010.RA_SEXO,
Nexti.dbo.FLEX_COLABORADOR.EMAIL = RTRIM(SRA010.RA_EMAIL),
Nexti.dbo.FLEX_COLABORADOR.TELEFONE = RTRIM(SRA010.RA_TELEFON),
Nexti.dbo.FLEX_COLABORADOR.TELEFONE2 = (CAST(RTRIM(SRA010.RA_DDDCELU) AS VARCHAR(100)) + CAST(RTRIM(SRA010.RA_NUMCELU) AS VARCHAR(100))),
Nexti.dbo.FLEX_COLABORADOR.NOME_PAI = RTRIM(SRA010.RA_PAI),
Nexti.dbo.FLEX_COLABORADOR.NOME_MAE = RTRIM(SRA010.RA_MAE),
Nexti.dbo.FLEX_COLABORADOR.TIPO = 1,
Nexti.dbo.FLEX_COLABORADOR.SITUACAO = 0
FROM Nexti.dbo.FLEX_COLABORADOR
JOIN TOTVS_12.dbo.SRA010 SRA010
	ON Nexti.dbo.FLEX_COLABORADOR.NUMCAD = SRA010.RA_MAT collate database_default
	AND Nexti.dbo.FLEX_COLABORADOR.CODFIL = SRA010.RA_FILIAL collate database_default
	AND Nexti.dbo.FLEX_COLABORADOR.NUMEMP = LEFT(SRA010.RA_FILIAL,2)
	AND LTRIM(RTRIM(SRA010.RA_DEMISSA)) = ''
	AND SRA010.D_E_L_E_T_ <> '*'
JOIN Nexti.dbo.FLEX_CARGO
    ON Nexti.dbo.FLEX_CARGO.CODCAR = SRA010.RA_CODFUNC collate database_default
    AND Nexti.dbo.FLEX_CARGO.CODFIL = LEFT(SRA010.RA_FILIAL,2) collate database_default
WHERE Nexti.dbo.FLEX_COLABORADOR.ID > 0
AND (
	Nexti.dbo.FLEX_COLABORADOR.CEP <> SRA010.RA_CEP collate database_default
	OR Nexti.dbo.FLEX_COLABORADOR.NOMFUN <> LTRIM(RTRIM(SRA010.RA_NOME)) collate database_default
	OR Nexti.dbo.FLEX_COLABORADOR.ENDERECO <> RTRIM(RA_ENDEREC) collate database_default
	OR Nexti.dbo.FLEX_COLABORADOR.COMPLEMENTO<> RTRIM(RA_COMPLEM) collate database_default
	OR Nexti.dbo.FLEX_COLABORADOR.NUMERO <> RTRIM(RA_NUMENDE) collate database_default
	OR Nexti.dbo.FLEX_COLABORADOR.BAIRRO <> RTRIM(RA_BAIRRO) collate database_default
	OR Nexti.dbo.FLEX_COLABORADOR.CIDADE <> (RA_MUNICIP) collate database_default
	OR Nexti.dbo.FLEX_COLABORADOR.ESTADO <> RTRIM(RA_ESTADO) collate database_default
	OR Nexti.dbo.FLEX_COLABORADOR.DATADMISSAO <> RA_ADMISSA collate database_default
	OR Nexti.dbo.FLEX_COLABORADOR.DATANASCIMENTO <> SRA010.RA_NASC collate database_default
	OR Nexti.dbo.FLEX_COLABORADOR.CARGO <> Nexti.dbo.FLEX_CARGO.IDEXTERNO collate database_default
	OR Nexti.dbo.FLEX_COLABORADOR.CPF <> RTRIM(SRA010.RA_CIC) collate database_default
	OR Nexti.dbo.FLEX_COLABORADOR.RG <> RTRIM(SRA010.RA_RG) collate database_default
	OR Nexti.dbo.FLEX_COLABORADOR.PIS <> RTRIM(SRA010.RA_PIS) collate database_default
	OR Nexti.dbo.FLEX_COLABORADOR.GENERO <> SRA010.RA_SEXO collate database_default
	OR Nexti.dbo.FLEX_COLABORADOR.EMAIL <> RTRIM(SRA010.RA_EMAIL) collate database_default
	OR Nexti.dbo.FLEX_COLABORADOR.TELEFONE <> RTRIM(SRA010.RA_TELEFON) collate database_default
	OR Nexti.dbo.FLEX_COLABORADOR.TELEFONE2 <> (CAST(RTRIM(SRA010.RA_DDDCELU) AS VARCHAR(100)) + CAST(RTRIM(SRA010.RA_NUMCELU) AS VARCHAR(100))) collate database_default
	OR Nexti.dbo.FLEX_COLABORADOR.NOME_PAI <> RTRIM(SRA010.RA_PAI) collate database_default
	OR Nexti.dbo.FLEX_COLABORADOR.NOME_MAE <> RTRIM(SRA010.RA_MAE) collate database_default
)