INSERT INTO nexti.dbo.FLEX_SINDICATOS
SELECT
RCE010.RCE_CODIGO AS CODSIN, 
(CAST(RCE010.RCE_CODIGO AS VARCHAR(100)) + ' - ' + CAST(RCE010.RCE_DESCRI AS VARCHAR(100))) AS NOMSIN, 
0 AS ID, 
R_E_C_N_O_ AS IDEXTERNO, 
0 AS TIPO, 
0 AS SITUACAO, 
'' AS OBSERVACAO
FROM ALIANCA.dbo.RCE010
WHERE RCE010.D_E_L_E_T_ = ''
AND NOT EXISTS (
	SELECT * FROM nexti.dbo.FLEX_SINDICATOS
	WHERE nexti.dbo.FLEX_SINDICATOS.IDEXTERNO = RCE010.R_E_C_N_O_
)
