INSERT INTO Nexti.dbo.FLEX_CARGO
SELECT 
SRJ010.R_E_C_N_O_,
SRJ010.RJ_FILIAL AS NUMEMP,
SRJ010.RJ_FILIAL AS CODFIL,
0 AS ID,
('01' + '-' + CAST(SRJ010.R_E_C_N_O_ AS VARCHAR(100))) AS IDEXTERNO,
(CAST(Nexti.dbo.FLEX_EMPRESA.IDEXTERNO AS VARCHAR(10)) + CAST(SRJ010.RJ_FUNCAO AS VARCHAR(10)) collate database_default) AS IDEXTERNO_OLD,
1 AS ESTCAR,
SRJ010.RJ_FUNCAO AS CODCAR, 
(CAST(RTRIM(SRJ010.RJ_FILIAL) AS VARCHAR(100)) + ' - ' + CAST(SRJ010.RJ_FUNCAO AS VARCHAR(100)) + ' - ' + CAST(SRJ010.RJ_DESC AS VARCHAR(100))) AS TITCAR,
0 AS TIPO,
0 AS SITUACAO,
'' AS OBSERVACAO
FROM TOTVS_12.dbo.SRJ010 SRJ010
LEFT JOIN Nexti.dbo.FLEX_EMPRESA
    ON Nexti.dbo.FLEX_EMPRESA.CODFIL = SRJ010.RJ_FILIAL collate database_default
    AND Nexti.dbo.FLEX_EMPRESA.NUMEMP = 1
WHERE SRJ010.D_E_L_E_T_ = ''
AND NOT EXISTS (
	SELECT * FROM Nexti.dbo.FLEX_CARGO
	WHERE Nexti.dbo.FLEX_CARGO.R_E_C_N_O_ = SRJ010.R_E_C_N_O_
)
AND SRJ010.RJ_DESC <> ''
AND SRJ010.RJ_DESC IS NOT NULL
AND SRJ010.RJ_FILIAL <> ''