INSERT INTO nexti.dbo.FLEX_CARGO
SELECT 
SRJ010.R_E_C_N_O_,
SRJ010.RJ_FILIAL AS NUMEMP,
'01' AS CODFIL,
0 AS ID,
('01' + '-' + CAST(SRJ010.R_E_C_N_O_ AS VARCHAR(100))) AS IDEXTERNO,
(CAST(nexti.dbo.FLEX_EMPRESA.IDEXTERNO AS VARCHAR(10)) + CAST(SRJ010.RJ_FUNCAO AS VARCHAR(10)) collate database_default) AS IDEXTERNO_OLD,
1 AS ESTCAR,
SRJ010.RJ_FUNCAO AS CODCAR, 
CAST(SRJ010.RJ_DESC AS VARCHAR(100)) AS TITCAR,
0 AS TIPO,
0 AS SITUACAO,
'' AS OBSERVACAO
FROM ALIANCA.dbo.SRJ010 SRJ010
LEFT JOIN nexti.dbo.FLEX_EMPRESA
    ON nexti.dbo.FLEX_EMPRESA.CODFIL = SRJ010.RJ_FILIAL collate database_default
    AND nexti.dbo.FLEX_EMPRESA.NUMEMP = 1
WHERE SRJ010.D_E_L_E_T_ = ''
AND NOT EXISTS (
	SELECT * FROM nexti.dbo.FLEX_CARGO
	WHERE nexti.dbo.FLEX_CARGO.R_E_C_N_O_ = SRJ010.R_E_C_N_O_
)
AND SRJ010.RJ_DESC <> ''
AND SRJ010.RJ_DESC IS NOT NULL