INSERT INTO Nexti.dbo.FLEX_POSTO
SELECT DISTINCT
CTT010.R_E_C_N_O_,
CTT010.CTT_FILIAL AS NUMEMP,
0 AS CODFIL,
0 AS ID,
CTT010.R_E_C_N_O_ AS IDEXTERNO,
0 AS ESTPOS,
LTRIM(RTRIM(CTT010.CTT_CUSTO)) AS POSTRA,
CONCAT(
  LTRIM(RTRIM(CTT010.CTT_CUSTO)) COLLATE DATABASE_DEFAULT,
  ' - ',
  LTRIM(RTRIM(CTT010.CTT_DESC01)) COLLATE DATABASE_DEFAULT
) AS DESPOS,
CTT010.CTT_CEP AS CEP,
CTT010.CTT_ENDER AS ENDERECO,
0 AS NUMERO,
CTT010.CTT_BAIRRO AS BAIRRO,
CTT010.CTT_CODMUN AS CIDADE,
CTT010.CTT_ESTADO AS ESTADO,
LTRIM(RTRIM(CTT010.CTT_CUSTO)) AS CODOEM,
LTRIM(RTRIM(CTT010.CTT_CUSTO)) AS CODCCU,
CTT010.CTT_DTEXIS AS DATCRI,
CTT010.CTT_DTEXSF AS DATEXT,
'America/Sao_Paulo' AS TIMEZONE,
0 AS VAGAS,
0 AS TIPO,
0 AS SITUACAO,
'' AS OBSERVACAO,
CTT010.CTT_BLOQ,
0 AS CTT_ZZCLVL,
0 AS UNIDADE_NEGOCIO,
'CCU' AS ORIGEM
FROM TOTVS_12.dbo.CTT010
JOIN Nexti.dbo.FLEX_EMPRESA
	ON Nexti.dbo.FLEX_EMPRESA.NUMEMP = CTT010.CTT_FILIAL collate database_default
JOIN Nexti.dbo.FLEX_CLIENTE
	ON Nexti.dbo.FLEX_CLIENTE.NUMEMP = CTT010.CTT_FILIAL collate database_default
	AND Nexti.dbo.FLEX_CLIENTE.CODOEM = LTRIM(RTRIM(CTT010.CTT_CUSTO)) collate database_default
WHERE LEN(CTT010.CTT_CUSTO) = 6
AND CTT010.CTT_BLOQ = 2
AND CTT010.D_E_L_E_T_ = ''
AND (
	EXISTS(
		SELECT * FROM TOTVS_12.dbo.SRE010
		WHERE SRE010.RE_CCP = CTT010.CTT_CUSTO
		AND SUBSTRING(RE_FILIALP,1,2) = CTT010.CTT_FILIAL
	)
	OR 
	EXISTS(
		SELECT * FROM TOTVS_12.dbo.SRE010
		WHERE SRE010.RE_CCD = CTT010.CTT_CUSTO
		AND SUBSTRING(RE_FILIALD,1,2) = CTT010.CTT_FILIAL
	)
	OR EXISTS(
		SELECT * FROM TOTVS_12.dbo.SRA010
		WHERE SRA010.D_E_L_E_T_ = ''
		AND (SRA010.RA_DEMISSA = '' OR SRA010.RA_DEMISSA IS NULL) 
		AND SRA010.RA_CC = CTT010.CTT_CUSTO
	)
)
AND NOT EXISTS(
	SELECT * FROM Nexti.dbo.FLEX_POSTO
	WHERE Nexti.dbo.FLEX_POSTO.IDEXTERNO = CTT010.R_E_C_N_O_ 
)