UPDATE nexti.dbo.FLEX_HORARIO
SET nexti.dbo.FLEX_HORARIO.CODHOR = (
	CASE
	    WHEN FLEX_HORARIO.ENTRADA2 = 0 AND FLEX_HORARIO.SAIDA2 = 0 THEN (
			REPLACE(
				REPLACE(
					IIF(CONVERT(VARCHAR(5), CAST(FLOOR(FLEX_HORARIO.ENTRADA1) AS INT)) = 0, '00', CONVERT(VARCHAR(5), CAST(FLOOR(FLEX_HORARIO.ENTRADA1) AS INT))) + ':' + 
						IIF(RIGHT(CONVERT(VARCHAR(4), CAST(FLEX_HORARIO.ENTRADA1 * 100 AS INT)), 2) = 0, '00', RIGHT(CONVERT(VARCHAR(4), CAST(FLEX_HORARIO.ENTRADA1 * 100 AS INT)), 2)) + 'as' +
					IIF(CONVERT(VARCHAR(5), CAST(FLOOR(FLEX_HORARIO.SAIDA1) AS INT)) = 0, '00', CONVERT(VARCHAR(5), CAST(FLOOR(FLEX_HORARIO.SAIDA1) AS INT))) + ':' + 
					    IIF(RIGHT(CONVERT(VARCHAR(4), CAST(FLEX_HORARIO.SAIDA1 * 100 AS INT)), 2) = 0, '00', RIGHT(CONVERT(VARCHAR(4), CAST(FLEX_HORARIO.SAIDA1 * 100 AS INT)), 2)), '.', ':'
				), ':00', ''
			) + CONVERT(VARCHAR(4), CAST(FLEX_HORARIO.INCREMENT * 1 AS INT))
		)
	    
	    ELSE (
			REPLACE(
				REPLACE(
					IIF(CONVERT(VARCHAR(5), CAST(FLOOR(FLEX_HORARIO.ENTRADA1) AS INT)) = 0, '00', CONVERT(VARCHAR(5), CAST(FLOOR(FLEX_HORARIO.ENTRADA1) AS INT))) + ':' + 
						IIF(RIGHT(CONVERT(VARCHAR(4), CAST(FLEX_HORARIO.ENTRADA1 * 100 AS INT)), 2) = 0, '00', RIGHT(CONVERT(VARCHAR(4), CAST(FLEX_HORARIO.ENTRADA1 * 100 AS INT)), 2)) + 'as' +
					IIF(CONVERT(VARCHAR(5), CAST(FLOOR(FLEX_HORARIO.SAIDA2) AS INT)) = 0, '00', CONVERT(VARCHAR(5), CAST(FLOOR(FLEX_HORARIO.SAIDA2) AS INT))) + ':' + 
					    IIF(RIGHT(CONVERT(VARCHAR(4), CAST(FLEX_HORARIO.SAIDA2 * 100 AS INT)), 2) = 0, '00', RIGHT(CONVERT(VARCHAR(4), CAST(FLEX_HORARIO.SAIDA2 * 100 AS INT)), 2)), '.', ':'
				), ':00', ''
			) + CONVERT(VARCHAR(4), CAST(FLEX_HORARIO.INCREMENT * 1 AS INT))
		)
	END
),
nexti.dbo.FLEX_HORARIO.IDEXTERNO = (
	CASE
	    WHEN FLEX_HORARIO.ENTRADA2 = 0 AND FLEX_HORARIO.SAIDA2 = 0 THEN (
			REPLACE(
				REPLACE(
					IIF(CONVERT(VARCHAR(5), CAST(FLOOR(FLEX_HORARIO.ENTRADA1) AS INT)) = 0, '00', CONVERT(VARCHAR(5), CAST(FLOOR(FLEX_HORARIO.ENTRADA1) AS INT))) + ':' + 
						IIF(RIGHT(CONVERT(VARCHAR(4), CAST(FLEX_HORARIO.ENTRADA1 * 100 AS INT)), 2) = 0, '00', RIGHT(CONVERT(VARCHAR(4), CAST(FLEX_HORARIO.ENTRADA1 * 100 AS INT)), 2)) + 'as' +
					IIF(CONVERT(VARCHAR(5), CAST(FLOOR(FLEX_HORARIO.SAIDA1) AS INT)) = 0, '00', CONVERT(VARCHAR(5), CAST(FLOOR(FLEX_HORARIO.SAIDA1) AS INT))) + ':' + 
					    IIF(RIGHT(CONVERT(VARCHAR(4), CAST(FLEX_HORARIO.SAIDA1 * 100 AS INT)), 2) = 0, '00', RIGHT(CONVERT(VARCHAR(4), CAST(FLEX_HORARIO.SAIDA1 * 100 AS INT)), 2)), '.', ':'
				), ':00', ''
			) + CONVERT(VARCHAR(4), CAST(FLEX_HORARIO.INCREMENT * 1 AS INT))
		)
	    
	    ELSE (
			REPLACE(
				REPLACE(
					IIF(CONVERT(VARCHAR(5), CAST(FLOOR(FLEX_HORARIO.ENTRADA1) AS INT)) = 0, '00', CONVERT(VARCHAR(5), CAST(FLOOR(FLEX_HORARIO.ENTRADA1) AS INT))) + ':' + 
						IIF(RIGHT(CONVERT(VARCHAR(4), CAST(FLEX_HORARIO.ENTRADA1 * 100 AS INT)), 2) = 0, '00', RIGHT(CONVERT(VARCHAR(4), CAST(FLEX_HORARIO.ENTRADA1 * 100 AS INT)), 2)) + 'as' +
					IIF(CONVERT(VARCHAR(5), CAST(FLOOR(FLEX_HORARIO.SAIDA2) AS INT)) = 0, '00', CONVERT(VARCHAR(5), CAST(FLOOR(FLEX_HORARIO.SAIDA2) AS INT))) + ':' + 
					    IIF(RIGHT(CONVERT(VARCHAR(4), CAST(FLEX_HORARIO.SAIDA2 * 100 AS INT)), 2) = 0, '00', RIGHT(CONVERT(VARCHAR(4), CAST(FLEX_HORARIO.SAIDA2 * 100 AS INT)), 2)), '.', ':'
				), ':00', ''
			) + CONVERT(VARCHAR(4), CAST(FLEX_HORARIO.INCREMENT * 1 AS INT))
		)
	END
)