INSERT INTO Nexti.dbo.FLEX_COLABORADOR
SELECT DISTINCT
SRA010.R_E_C_N_O_,
Nexti.dbo.FLEX_EMPRESA.NUMEMP AS NUMEMP,
SRA010.RA_FILIAL AS CODFIL,
0 AS ID,
SRA010.R_E_C_N_O_ AS IDEXTERNO,
1 AS TIPCOL,
SRA010.RA_MAT AS NUMCAD,
LTRIM(RTRIM(SRA010.RA_NOME)) AS NOMFUN,
SRA010.RA_CEP AS CEP,
LTRIM(RTRIM(SRA010.RA_ENDEREC)) AS ENDERECO,
LTRIM(RTRIM(SRA010.RA_COMPLEM)) AS COMPLEMENTO,
LTRIM(RTRIM(SRA010.RA_NUMENDE)) AS NUMERO,
LTRIM(RTRIM(SRA010.RA_BAIRRO)) AS BAIRRO,
LTRIM(RTRIM(SRA010.RA_MUNICIP)) AS CIDADE,
LTRIM(RTRIM(SRA010.RA_ESTADO)) AS ESTADO,
RA_ADMISSA AS DATADMISSAO,
SRA010.RA_NASC AS BIRTHDATE,
Nexti.dbo.FLEX_CARGO.IDEXTERNO AS CARGO,
0 AS IDEMPRESA,
LTRIM(RTRIM(SRA010.RA_CIC)) AS CPF,
LTRIM(RTRIM(SRA010.RA_RG)) AS RG,
LTRIM(RTRIM(SRA010.RA_PIS)) AS PIS,
SRA010.RA_SEXO AS GENERO,
LTRIM(RTRIM(SRA010.RA_EMAIL)) AS EMAIL,
LTRIM(RTRIM(SRA010.RA_TELEFON)) AS TELEFONE,
(CAST(LTRIM(RTRIM(SRA010.RA_DDDCELU)) AS VARCHAR(100)) + CAST(LTRIM(RTRIM(SRA010.RA_NUMCELU)) AS VARCHAR(100))) AS TELEFONE2,
LTRIM(RTRIM(SRA010.RA_PAI)) AS NOME_PAI,
LTRIM(RTRIM(SRA010.RA_MAE)) AS NOME_MAE,
0 AS TIPO,
0 AS SITUACAO,
'' AS OBSERVACAO,
NULL AS ESCALA,
1 AS TURMA,
SRA010.RA_DEMISSA AS DATADEMISSAO,
LTRIM(RTRIM(SRA010.RA_ORGEMRG)) AS RG_EMISSOR,
LTRIM(RTRIM(SRA010.RA_LOGRTP)) AS TIPOEND
FROM TOTVS_12.dbo.SRA010 SRA010
JOIN Nexti.dbo.FLEX_CARGO
    ON Nexti.dbo.FLEX_CARGO.CODCAR = SRA010.RA_CODFUNC collate database_default
    AND Nexti.dbo.FLEX_CARGO.CODFIL = LEFT(SRA010.RA_FILIAL,2) collate database_default
JOIN Nexti.dbo.FLEX_EMPRESA
    ON Nexti.dbo.FLEX_EMPRESA.NUMEMP = LEFT(SRA010.RA_FILIAL,2) collate database_default
WHERE SRA010.D_E_L_E_T_ = ''
AND (SRA010.RA_DEMISSA = '' OR SRA010.RA_DEMISSA IS NULL)
AND NOT EXISTS(
    SELECT * FROM Nexti.dbo.FLEX_COLABORADOR
    WHERE Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO = SRA010.R_E_C_N_O_
)