UPDATE Nexti.dbo.FLEX_COLABORADOR 
SET TIPO = 3, SITUACAO = 0
WHERE EXISTS(
		SELECT 1 FROM TOTVS_12.dbo.SRA010 SRA010
		WHERE SRA010.R_E_C_N_O_ = Nexti.dbo.FLEX_COLABORADOR.R_E_C_N_O_
		AND SRA010.D_E_L_E_T_ = '*'
	)