INSERT INTO Nexti.dbo.FLEX_ESCALA
SELECT 
0 AS R_E_C_N_O_,
0 AS NUMEMP,
0 AS CODFIL,
0 AS ID,
LTRIM(RTRIM(SR6010.R6_TURNO)) AS IDEXTERNO,
LTRIM(RTRIM(SR6010.R6_TURNO)) AS CODESC,
LTRIM(RTRIM(SR6010.R6_DESC)) AS NOMESC,
LTRIM(RTRIM(SR6010.R6_DESC)) AS NOME_COMPLETO,
0 AS TIPO,
0 AS SITUACAO,
'' AS OBSERVACAO,
'S' AS INTEGRA
FROM TOTVS_12.dbo.SR6010 SR6010
WHERE SR6010.D_E_L_E_T_ = ''
AND NOT EXISTS(
	SELECT * FROM Nexti.dbo.FLEX_ESCALA
	WHERE Nexti.dbo.FLEX_ESCALA.IDEXTERNO = LTRIM(RTRIM(SR6010.R6_TURNO)) collate database_default
)
GROUP BY SR6010.R6_TURNO,
SR6010.R6_DESC