INSERT INTO nexti.dbo.FLEX_ESCALA_HORARIO
SELECT 
'1' AS NUMEMP,
'01' AS CODFIL,
nexti.dbo.FLEX_ESCALA.CODESC,
SPJ010.PJ_SEMANA,
nexti.dbo.FLEX_HORARIO.CODHOR,
SPJ010.PJ_TPDIA AS TIPO_DIA,
SPJ010.PJ_DIA,
0 AS TIPO,
0 AS SITUACAO ,
'' AS OBSERVACAO
FROM ALIANCA.dbo.SPJ010
JOIN nexti.dbo.FLEX_ESCALA
	ON nexti.dbo.FLEX_ESCALA.CODESC = SPJ010.PJ_TURNO collate database_default
JOIN nexti.dbo.FLEX_HORARIO
	ON nexti.dbo.FLEX_HORARIO.ENTRADA1 = SPJ010.PJ_ENTRA1
	AND nexti.dbo.FLEX_HORARIO.SAIDA1 = SPJ010.PJ_SAIDA1
	AND nexti.dbo.FLEX_HORARIO.ENTRADA2 = SPJ010.PJ_ENTRA2
	AND nexti.dbo.FLEX_HORARIO.SAIDA2 = SPJ010.PJ_SAIDA2
WHERE SPJ010.D_E_L_E_T_ = ''
AND NOT EXISTS(
	SELECT * FROM nexti.dbo.FLEX_ESCALA_HORARIO
	WHERE nexti.dbo.FLEX_ESCALA_HORARIO.CODESC = nexti.dbo.FLEX_ESCALA.CODESC
	AND nexti.dbo.FLEX_ESCALA_HORARIO.SEMANA = SPJ010.PJ_SEMANA
	AND nexti.dbo.FLEX_ESCALA_HORARIO.CODHOR = nexti.dbo.FLEX_HORARIO.CODHOR
	AND nexti.dbo.FLEX_ESCALA_HORARIO.DIA = SPJ010.PJ_DIA
)
GROUP BY 
nexti.dbo.FLEX_ESCALA.CODESC,
SPJ010.PJ_SEMANA,
SPJ010.PJ_DIA,
SPJ010.PJ_TPDIA,
nexti.dbo.FLEX_HORARIO.CODHOR
ORDER BY 
nexti.dbo.FLEX_ESCALA.CODESC,
SPJ010.PJ_SEMANA