INSERT INTO nexti.dbo.FLEX_ESCALA_HORARIO
SELECT 
'1' AS NUMEMP,
'01' AS CODFIL,
nexti.dbo.FLEX_ESCALA.CODESC,
1 AS SEMANA,
0 AS CODHOR,
'D' AS TIPO_DIA,
1 DIA,
0 AS TIPO,
0 AS SITUACAO ,
'' AS OBSERVACAO
FROM nexti.dbo.FLEX_ESCALA
WHERE NOT EXISTS(
	SELECT * FROM nexti.dbo.FLEX_ESCALA_HORARIO
	WHERE nexti.dbo.FLEX_ESCALA_HORARIO.CODESC = FLEX_ESCALA.CODESC
	AND nexti.dbo.FLEX_ESCALA_HORARIO.SEMANA = 1
	AND nexti.dbo.FLEX_ESCALA_HORARIO.DIA = 1
)
AND EXISTS(
	SELECT * FROM nexti.dbo.FLEX_ESCALA_HORARIO
	WHERE nexti.dbo.FLEX_ESCALA_HORARIO.CODESC = FLEX_ESCALA.CODESC
	AND nexti.dbo.FLEX_ESCALA_HORARIO.SEMANA = 1
)