INSERT INTO Nexti.dbo.FLEX_ESCALA_HORARIO
SELECT 
0 AS NUMEMP,
0 AS CODFIL,
Nexti.dbo.FLEX_ESCALA.CODESC,
SPJ010.PJ_SEMANA,
Nexti.dbo.FLEX_HORARIO.CODHOR,
SPJ010.PJ_TPDIA AS TIPO_DIA,
SPJ010.PJ_DIA,
0 AS TIPO,
0 AS SITUACAO ,
'' AS OBSERVACAO
FROM TOTVS_12.dbo.SPJ010
JOIN Nexti.dbo.FLEX_ESCALA
	ON Nexti.dbo.FLEX_ESCALA.CODESC = SPJ010.PJ_TURNO collate database_default
JOIN Nexti.dbo.FLEX_HORARIO
	ON Nexti.dbo.FLEX_HORARIO.ENTRADA1 = SPJ010.PJ_ENTRA1
	AND Nexti.dbo.FLEX_HORARIO.SAIDA1 = SPJ010.PJ_SAIDA1
	AND Nexti.dbo.FLEX_HORARIO.ENTRADA2 = SPJ010.PJ_ENTRA2
	AND Nexti.dbo.FLEX_HORARIO.SAIDA2 = SPJ010.PJ_SAIDA2
WHERE SPJ010.D_E_L_E_T_ = ''
AND NOT EXISTS(
	SELECT * FROM Nexti.dbo.FLEX_ESCALA_HORARIO
	WHERE Nexti.dbo.FLEX_ESCALA_HORARIO.CODESC = Nexti.dbo.FLEX_ESCALA.CODESC
	AND Nexti.dbo.FLEX_ESCALA_HORARIO.SEMANA = SPJ010.PJ_SEMANA
	AND Nexti.dbo.FLEX_ESCALA_HORARIO.CODHOR = Nexti.dbo.FLEX_HORARIO.CODHOR
	AND Nexti.dbo.FLEX_ESCALA_HORARIO.DIA = SPJ010.PJ_DIA
)
GROUP BY 
Nexti.dbo.FLEX_ESCALA.CODESC,
SPJ010.PJ_SEMANA,
SPJ010.PJ_DIA,
SPJ010.PJ_TPDIA,
Nexti.dbo.FLEX_HORARIO.CODHOR
ORDER BY 
Nexti.dbo.FLEX_ESCALA.CODESC,
SPJ010.PJ_SEMANA