INSERT INTO nexti.dbo.FLEX_ESCALA_TURMA
SELECT
'1' AS NUMEMP,
'01' AS CODFIL,
0 AS ID,
'' AS IDEXTERNO,
SPJ010.PJ_TURNO AS CODESC,
SPJ010.PJ_SEMANA AS CODTMA,
CONVERT(DATE,'1940-01-01',120) AS DATBAS,
0 AS TIPO,
0 AS SITUACAO,
'' AS OBSERVACAO,
0 AS DIA_INICIO
FROM ALIANCA.dbo.SPJ010
JOIN nexti.dbo.FLEX_ESCALA
	ON nexti.dbo.FLEX_ESCALA.CODESC = SPJ010.PJ_TURNO collate database_default
WHERE SPJ010.D_E_L_E_T_ = ''
AND NOT EXISTS(
	SELECT * FROM nexti.dbo.FLEX_ESCALA_TURMA
	WHERE nexti.dbo.FLEX_ESCALA_TURMA.CODESC = SPJ010.PJ_TURNO collate database_default
	AND nexti.dbo.FLEX_ESCALA_TURMA.CODTMA = SPJ010.PJ_SEMANA collate database_default
)
GROUP BY SPJ010.PJ_TURNO, SPJ010.PJ_SEMANA
ORDER BY SPJ010.PJ_TURNO, SPJ010.PJ_SEMANA