INSERT INTO Nexti.dbo.FLEX_ESCALA_TURMA
SELECT
0 AS NUMEMP,
0 AS CODFIL,
0 AS ID,
'' AS IDEXTERNO,
SPJ010.PJ_TURNO AS CODESC,
SPJ010.PJ_SEMANA AS CODTMA,
CONVERT(DATE,'1940-01-01',120) AS DATBAS,
0 AS TIPO,
0 AS SITUACAO,
'' AS OBSERVACAO,
0 AS DIA_INICIO
FROM TOTVS_12.dbo.SPJ010
JOIN Nexti.dbo.FLEX_ESCALA
	ON Nexti.dbo.FLEX_ESCALA.CODESC = SPJ010.PJ_TURNO collate database_default
WHERE SPJ010.D_E_L_E_T_ = ''
AND NOT EXISTS(
	SELECT * FROM Nexti.dbo.FLEX_ESCALA_TURMA
	WHERE Nexti.dbo.FLEX_ESCALA_TURMA.CODESC = SPJ010.PJ_TURNO collate database_default
	AND Nexti.dbo.FLEX_ESCALA_TURMA.CODTMA = SPJ010.PJ_SEMANA collate database_default
)
GROUP BY SPJ010.PJ_TURNO, SPJ010.PJ_SEMANA
ORDER BY SPJ010.PJ_TURNO, SPJ010.PJ_SEMANA