INSERT INTO Nexti.dbo.FLEX_ESCALA_HORARIO
SELECT 
0 AS NUMEMP,
0 AS CODFIL,
Nexti.dbo.FLEX_ESCALA.CODESC,
2 AS SEMANA,
0 AS CODHOR,
'D' AS TIPO_DIA,
1 DIA,
0 AS TIPO,
0 AS SITUACAO ,
'' AS OBSERVACAO
FROM Nexti.dbo.FLEX_ESCALA
WHERE NOT EXISTS(
	SELECT * FROM Nexti.dbo.FLEX_ESCALA_HORARIO
	WHERE Nexti.dbo.FLEX_ESCALA_HORARIO.CODESC = FLEX_ESCALA.CODESC
	AND Nexti.dbo.FLEX_ESCALA_HORARIO.SEMANA = 2
	AND Nexti.dbo.FLEX_ESCALA_HORARIO.DIA = 1
)
AND EXISTS(
	SELECT * FROM Nexti.dbo.FLEX_ESCALA_HORARIO
	WHERE Nexti.dbo.FLEX_ESCALA_HORARIO.CODESC = FLEX_ESCALA.CODESC
	AND Nexti.dbo.FLEX_ESCALA_HORARIO.SEMANA = 2
)