UPDATE Nexti.dbo.FLEX_POSTO
SET Nexti.dbo.FLEX_POSTO.CTT_BLOQ = 1,
Nexti.dbo.FLEX_POSTO.TIPO = 1,
Nexti.dbo.FLEX_POSTO.SITUACAO = 0
FROM Nexti.dbo.FLEX_POSTO
JOIN TOTVS_12.dbo.CTT010 CTT010
	ON CTT010.R_E_C_N_O_ = Nexti.dbo.FLEX_POSTO.R_E_C_N_O_
	AND CTT010.D_E_L_E_T_ = ''
WHERE Nexti.dbo.FLEX_POSTO.ID > 0
AND Nexti.dbo.FLEX_POSTO.CTT_BLOQ = 2
AND CTT010.CTT_BLOQ = '1'
