UPDATE nexti.dbo.FLEX_POSTO
SET nexti.dbo.FLEX_POSTO.CTT_BLOQ = 1,
nexti.dbo.FLEX_POSTO.TIPO = 1,
nexti.dbo.FLEX_POSTO.SITUACAO = 0
FROM nexti.dbo.FLEX_POSTO
JOIN ALIANCA.dbo.CTT010 CTT010
	ON CTT010.R_E_C_N_O_ = nexti.dbo.FLEX_POSTO.R_E_C_N_O_
	AND CTT010.D_E_L_E_T_ = ''
WHERE nexti.dbo.FLEX_POSTO.ID > 0
AND nexti.dbo.FLEX_POSTO.CTT_BLOQ = 2
AND CTT010.CTT_BLOQ = '1'
