INSERT INTO nexti.dbo.FLEX_TROCA_SINDICATO_PROTHEUS
SELECT
nexti.dbo.FLEX_COLABORADOR.NUMEMP,
nexti.dbo.FLEX_COLABORADOR.CODFIL,
nexti.dbo.FLEX_COLABORADOR.TIPCOL,
nexti.dbo.FLEX_COLABORADOR.NUMCAD,
GETDATE() AS DATALT,
SRA010.RA_SINDICA as CODSIN,
0 AS TIPO,
0 AS SITUACAO,
'' AS OBSERVACAO,
0 AS ID,
SRA010.R_E_C_N_O_ AS IDEXTERNO
FROM nexti.dbo.FLEX_COLABORADOR
JOIN ALIANCA.dbo.SRA010 SRA010
	ON SRA010.R_E_C_N_O_ = nexti.dbo.FLEX_COLABORADOR.R_E_C_N_O_
JOIN nexti.dbo.FLEX_SINDICATOS
	ON nexti.dbo.FLEX_SINDICATOS.CODSIN = SRA010.RA_SINDICA
WHERE (
	nexti.dbo.FLEX_COLABORADOR.DATADEMISSAO IS NULL
	OR nexti.dbo.FLEX_COLABORADOR.DATADEMISSAO = ''
)
AND NOT EXISTS 
(
	SELECT * FROM nexti.dbo.FLEX_TROCA_SINDICATO_PROTHEUS
	WHERE nexti.dbo.FLEX_TROCA_SINDICATO_PROTHEUS.IDEXTERNO = nexti.dbo.FLEX_COLABORADOR.IDEXTERNO
	AND nexti.dbo.FLEX_TROCA_SINDICATO_PROTHEUS.CODSIN = SRA010.RA_SINDICA collate database_default
	AND nexti.dbo.FLEX_TROCA_SINDICATO_PROTHEUS.DATALT = (
		SELECT MAX(NTS.DATALT) FROM nexti.dbo.FLEX_TROCA_SINDICATO_PROTHEUS NTS
		WHERE NTS.NUMEMP = nexti.dbo.FLEX_COLABORADOR.NUMEMP
		AND NTS.CODFIL = nexti.dbo.FLEX_COLABORADOR.CODFIL
		AND NTS.TIPCOL = nexti.dbo.FLEX_COLABORADOR.TIPCOL
		AND NTS.NUMCAD = nexti.dbo.FLEX_COLABORADOR.NUMCAD
	)
)