INSERT INTO Nexti.dbo.FLEX_TROCA_SINDICATO_PROTHEUS
SELECT
Nexti.dbo.FLEX_COLABORADOR.NUMEMP,
Nexti.dbo.FLEX_COLABORADOR.CODFIL,
Nexti.dbo.FLEX_COLABORADOR.TIPCOL,
Nexti.dbo.FLEX_COLABORADOR.NUMCAD,
GETDATE() AS DATALT,
SRA010.RA_SINDICA as CODSIN,
0 AS TIPO,
0 AS SITUACAO,
'' AS OBSERVACAO,
0 AS ID,
SRA010.R_E_C_N_O_ AS IDEXTERNO
FROM Nexti.dbo.FLEX_COLABORADOR
JOIN TOTVS_12.dbo.SRA010 SRA010
	ON SRA010.R_E_C_N_O_ = Nexti.dbo.FLEX_COLABORADOR.R_E_C_N_O_
JOIN Nexti.dbo.FLEX_SINDICATOS
	ON Nexti.dbo.FLEX_SINDICATOS.CODSIN = SRA010.RA_SINDICA
WHERE (
	Nexti.dbo.FLEX_COLABORADOR.DATADEMISSAO IS NULL
	OR Nexti.dbo.FLEX_COLABORADOR.DATADEMISSAO = ''
)
AND NOT EXISTS 
(
	SELECT * FROM Nexti.dbo.FLEX_TROCA_SINDICATO_PROTHEUS
	WHERE Nexti.dbo.FLEX_TROCA_SINDICATO_PROTHEUS.IDEXTERNO = Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO
	AND Nexti.dbo.FLEX_TROCA_SINDICATO_PROTHEUS.CODSIN = SRA010.RA_SINDICA collate database_default
	AND Nexti.dbo.FLEX_TROCA_SINDICATO_PROTHEUS.DATALT = (
		SELECT MAX(NTS.DATALT) FROM Nexti.dbo.FLEX_TROCA_SINDICATO_PROTHEUS NTS
		WHERE NTS.NUMEMP = Nexti.dbo.FLEX_COLABORADOR.NUMEMP
		AND NTS.CODFIL = Nexti.dbo.FLEX_COLABORADOR.CODFIL
		AND NTS.TIPCOL = Nexti.dbo.FLEX_COLABORADOR.TIPCOL
		AND NTS.NUMCAD = Nexti.dbo.FLEX_COLABORADOR.NUMCAD
	)
)