UPDATE Nexti.dbo.FLEX_ESCALA
SET Nexti.dbo.FLEX_ESCALA.TIPO = 1,
Nexti.dbo.FLEX_ESCALA.SITUACAO = 0
WHERE EXISTS(
	SELECT * FROM Nexti.dbo.FLEX_ESCALA_HORARIO
	WHERE Nexti.dbo.FLEX_ESCALA_HORARIO.NUMEMP = Nexti.dbo.FLEX_ESCALA.NUMEMP
	AND Nexti.dbo.FLEX_ESCALA_HORARIO.CODFIL = Nexti.dbo.FLEX_ESCALA.CODFIL
	AND Nexti.dbo.FLEX_ESCALA_HORARIO.CODESC = Nexti.dbo.FLEX_ESCALA.CODESC
	AND Nexti.dbo.FLEX_ESCALA_HORARIO.SITUACAO IN(0,2)
)
AND Nexti.dbo.FLEX_ESCALA.SITUACAO = 1
AND Nexti.dbo.FLEX_ESCALA.ID > 0