UPDATE nexti.dbo.FLEX_ESCALA
SET nexti.dbo.FLEX_ESCALA.TIPO = 1,
nexti.dbo.FLEX_ESCALA.SITUACAO = 0
WHERE EXISTS(
	SELECT * FROM nexti.dbo.FLEX_ESCALA_HORARIO
	WHERE nexti.dbo.FLEX_ESCALA_HORARIO.NUMEMP = nexti.dbo.FLEX_ESCALA.NUMEMP
	AND nexti.dbo.FLEX_ESCALA_HORARIO.CODFIL = nexti.dbo.FLEX_ESCALA.CODFIL
	AND nexti.dbo.FLEX_ESCALA_HORARIO.CODESC = nexti.dbo.FLEX_ESCALA.CODESC
	AND nexti.dbo.FLEX_ESCALA_HORARIO.SITUACAO IN(0,2)
)
AND nexti.dbo.FLEX_ESCALA.SITUACAO = 1
AND nexti.dbo.FLEX_ESCALA.ID > 0