DELETE FROM Nexti.dbo.FLEX_ESCALA_HORARIO
WHERE EXISTS(
	SELECT * FROM Nexti.dbo.FLEX_ESCALA
	WHERE Nexti.dbo.FLEX_ESCALA.CODESC = Nexti.dbo.FLEX_ESCALA_HORARIO.CODESC
	AND Nexti.dbo.FLEX_ESCALA.SITUACAO IN(0,2)
)