DELETE FROM nexti.dbo.FLEX_ESCALA_HORARIO
WHERE EXISTS(
	SELECT * FROM nexti.dbo.FLEX_ESCALA
	WHERE nexti.dbo.FLEX_ESCALA.CODESC = nexti.dbo.FLEX_ESCALA_HORARIO.CODESC
	AND nexti.dbo.FLEX_ESCALA.SITUACAO IN(0,2)
)