INSERT INTO Nexti.dbo.FLEX_AVISOS
SELECT 
Nexti.dbo.FLEX_COLABORADOR.ID AS IDCOLABORADOR,
Nexti.dbo.FLEX_COLABORADOR.NUMEMP,
SRH010.RH_FILIAL AS CODFIL,
Nexti.dbo.FLEX_COLABORADOR.TIPCOL,
Nexti.dbo.FLEX_COLABORADOR.NUMCAD,
Nexti.dbo.FLEX_COLABORADOR.NOMFUN,
Nexti.dbo.FLEX_COLABORADOR.CPF,
'Recibo de Férias' AS NOME,
SRH010.RH_DATAINI AS STARTDATE,
SRH010.RH_DATAFIM AS FINISHDATE,
SRH010.RH_DATABAS AS STARTDATE_AQUI,
SRH010.RH_DBASEAT AS FINISHDATE_AQUI,
SRH010.RH_DTAVISO AS DATAPGTO,
0 AS REMOVIDO,
'0' AS ARQUIVO,
0 AS TIPO,
0 AS SITUACAO,
'' AS OBSERVACAO,
0 AS ID
FROM TOTVS_12.dbo.SRH010
JOIN TOTVS_12.dbo.SRA010
	ON SRA010.RA_FILIAL = SRH010.RH_FILIAL
	AND SRA010.RA_MAT = SRH010.RH_MAT
JOIN Nexti.dbo.FLEX_COLABORADOR
	ON Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO = SRA010.R_E_C_N_O_
WHERE SRH010.RH_DATAINI >= (SELECT DATEADD(dd,datediff(dd,0,DATEADD(DAY, 0, GETDATE())),0))
AND SRH010.RH_DATAINI <= (SELECT DATEADD(dd,datediff(dd,0,DATEADD(DAY, 2, GETDATE())),0))
AND SRH010.D_E_L_E_T_ = ''
AND NOT EXISTS(
	SELECT * FROM Nexti.dbo.FLEX_AVISOS
	WHERE Nexti.dbo.FLEX_AVISOS.NUMEMP = Nexti.dbo.FLEX_COLABORADOR.NUMEMP
	AND Nexti.dbo.FLEX_AVISOS.CODFIL = Nexti.dbo.FLEX_COLABORADOR.CODFIL
	AND Nexti.dbo.FLEX_AVISOS.NUMCAD = Nexti.dbo.FLEX_COLABORADOR.NUMCAD
	AND Nexti.dbo.FLEX_AVISOS.STARTDATE = SRH010.RH_DATAINI
	AND Nexti.dbo.FLEX_AVISOS.FINISHDATE = SRH010.RH_DATAFIM
	AND Nexti.dbo.FLEX_AVISOS.DATAPGTO = SRH010.RH_DTAVISO
	AND Nexti.dbo.FLEX_AVISOS.NOME = 'Recibo de Férias'
)