INSERT INTO nexti.dbo.FLEX_AVISOS
SELECT 
nexti.dbo.FLEX_COLABORADOR.ID AS IDCOLABORADOR,
nexti.dbo.FLEX_COLABORADOR.NUMEMP,
SRH010.RH_FILIAL AS CODFIL,
nexti.dbo.FLEX_COLABORADOR.TIPCOL,
nexti.dbo.FLEX_COLABORADOR.NUMCAD,
nexti.dbo.FLEX_COLABORADOR.NOMFUN,
nexti.dbo.FLEX_COLABORADOR.CPF,
'Recibo de Férias' AS NOME,
SRH010.RH_DATAINI AS STARTDATE,
SRH010.RH_DATAFIM AS FINISHDATE,
SRH010.RH_DATABAS AS STARTDATE_AQUI,
SRH010.RH_DBASEAT AS FINISHDATE_AQUI,
SRH010.RH_DTAVISO AS DATAPGTO,
0 AS REMOVIDO,
'0' AS ARQUIVO,
0 AS TIPO,
0 AS SITUACAO,
'' AS OBSERVACAO,
0 AS ID
FROM ALIANCA.dbo.SRH010
JOIN ALIANCA.dbo.SRA010
	ON SRA010.RA_FILIAL = SRH010.RH_FILIAL
	AND SRA010.RA_MAT = SRH010.RH_MAT
JOIN nexti.dbo.FLEX_COLABORADOR
	ON nexti.dbo.FLEX_COLABORADOR.IDEXTERNO = SRA010.R_E_C_N_O_
WHERE SRH010.RH_DATAINI >= (SELECT DATEADD(dd,datediff(dd,0,DATEADD(DAY, 0, GETDATE())),0))
AND SRH010.RH_DATAINI <= (SELECT DATEADD(dd,datediff(dd,0,DATEADD(DAY, 2, GETDATE())),0))
AND SRH010.D_E_L_E_T_ = ''
AND NOT EXISTS(
	SELECT * FROM nexti.dbo.FLEX_AVISOS
	WHERE nexti.dbo.FLEX_AVISOS.NUMEMP = nexti.dbo.FLEX_COLABORADOR.NUMEMP
	AND nexti.dbo.FLEX_AVISOS.CODFIL = nexti.dbo.FLEX_COLABORADOR.CODFIL
	AND nexti.dbo.FLEX_AVISOS.NUMCAD = nexti.dbo.FLEX_COLABORADOR.NUMCAD
	AND nexti.dbo.FLEX_AVISOS.STARTDATE = SRH010.RH_DATAINI
	AND nexti.dbo.FLEX_AVISOS.FINISHDATE = SRH010.RH_DATAFIM
	AND nexti.dbo.FLEX_AVISOS.DATAPGTO = SRH010.RH_DTAVISO
	AND nexti.dbo.FLEX_AVISOS.NOME = 'Recibo de Férias'
)