UPDATE Nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS
SET Nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.TIPO = 3,
Nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.SITUACAO = 0
WHERE  Nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.ORIGEM = 'A'
AND NOT EXISTS(
	SELECT * FROM  Nexti.dbo.FLEX_COLABORADOR
	WHERE  Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO =  Nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.IDEXTERNO
	AND  Nexti.dbo.FLEX_COLABORADOR.DATADMISSAO =  Nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.DATALT
)
AND Nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.ID > 0