UPDATE nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS
SET nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.TIPO = 3,
nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.SITUACAO = 0
WHERE  nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.ORIGEM = 'A'
AND NOT EXISTS(
	SELECT * FROM  nexti.dbo.FLEX_COLABORADOR
	WHERE  nexti.dbo.FLEX_COLABORADOR.IDEXTERNO =  nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.IDEXTERNO
	AND  nexti.dbo.FLEX_COLABORADOR.DATADMISSAO =  nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.DATALT
)
AND nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.ID > 0