UPDATE FLEX_TROCA_ESCALA_PROTHEUS
SET FLEX_TROCA_ESCALA_PROTHEUS.TIPO = 3,
FLEX_TROCA_ESCALA_PROTHEUS.SITUACAO = 0
WHERE FLEX_TROCA_ESCALA_PROTHEUS.ID > 0
AND NOT EXISTS(
    SELECT * FROM TOTVS_12.dbo.SPF010
    JOIN TOTVS_12.dbo.SRA010
        ON SRA010.RA_MAT = SPF010.PF_MAT
        AND SRA010.RA_FILIAL = SPF010.PF_FILIAL
    JOIN Nexti.dbo.FLEX_COLABORADOR
        ON Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO = SRA010.R_E_C_N_O_ 
        AND Nexti.dbo.FLEX_COLABORADOR.ID > 0
        
    WHERE Nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.IDEXTERNO = Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO
    AND Nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.DATALT = SPF010.PF_DATA
    AND Nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.TURMA = CAST(SPF010.PF_SEQUEPA AS INT)
    AND Nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.ESCALA = SPF010.PF_TURNOPA collate database_default
    AND  TOTVS_12.dbo.SPF010.D_E_L_E_T_ = ''
)
AND FLEX_TROCA_ESCALA_PROTHEUS.ORIGEM = 'H'