UPDATE FLEX_TROCA_ESCALA_PROTHEUS
SET FLEX_TROCA_ESCALA_PROTHEUS.TIPO = 3,
FLEX_TROCA_ESCALA_PROTHEUS.SITUACAO = 0
WHERE FLEX_TROCA_ESCALA_PROTHEUS.ID > 0
AND NOT EXISTS(
    SELECT * FROM ALIANCA.dbo.SPF010
    JOIN ALIANCA.dbo.SRA010
        ON SRA010.RA_MAT = SPF010.PF_MAT
        AND SRA010.RA_FILIAL = SPF010.PF_FILIAL
    JOIN nexti.dbo.FLEX_COLABORADOR
        ON nexti.dbo.FLEX_COLABORADOR.IDEXTERNO = SRA010.R_E_C_N_O_ 
        AND nexti.dbo.FLEX_COLABORADOR.ID > 0
        
    WHERE nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.IDEXTERNO = nexti.dbo.FLEX_COLABORADOR.IDEXTERNO
    AND nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.DATALT = SPF010.PF_DATA
    AND nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.TURMA = CAST(SPF010.PF_SEQUEPA AS INT)
    AND nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.ESCALA = SPF010.PF_TURNOPA collate database_default
    AND  ALIANCA.dbo.SPF010.D_E_L_E_T_ = ''
)
AND FLEX_TROCA_ESCALA_PROTHEUS.ORIGEM = 'H'