INSERT INTO Nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS
SELECT DISTINCT
	FLEX_COLABORADOR.NUMEMP,
	FLEX_COLABORADOR.CODFIL,
	FLEX_COLABORADOR.TIPCOL,
	FLEX_COLABORADOR.NUMCAD,
	FLEX_COLABORADOR.DATADMISSAO AS DATALT,
   	FLEX_ESCALA.IDEXTERNO AS ESCALA,
    1 AS TURMA,
	0 AS TIPO,
	0 AS SITUACAO,
	'' AS OBSERVACAO,
	0 AS ID,
	FLEX_COLABORADOR.IDEXTERNO AS IDEXTERNO,
	'C' AS ORIGEM 
FROM Nexti.dbo.FLEX_COLABORADOR
JOIN TOTVS_12.dbo.SRA010
	ON(FLEX_COLABORADOR.IDEXTERNO = SRA010.R_E_C_N_O_
		AND FLEX_COLABORADOR.ID > 0
    )
JOIN Nexti.dbo.FLEX_ESCALA
	ON(
		Nexti.dbo.FLEX_ESCALA.CODESC = SRA010.RA_TNOTRAB collate database_default
		AND Nexti.dbo.FLEX_ESCALA.ID > 0
	)
WHERE NOT EXISTS(
	SELECT
		1
	FROM FLEX_TROCA_ESCALA_PROTHEUS
	WHERE FLEX_COLABORADOR.IDEXTERNO = FLEX_TROCA_ESCALA_PROTHEUS.IDEXTERNO
	AND FLEX_COLABORADOR.DATADMISSAO = FLEX_TROCA_ESCALA_PROTHEUS.DATALT
)