INSERT INTO Nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS
SELECT DISTINCT
Nexti.dbo.FLEX_COLABORADOR.NUMEMP,
Nexti.dbo.FLEX_COLABORADOR.CODFIL,
Nexti.dbo.FLEX_COLABORADOR.TIPCOL,
Nexti.dbo.FLEX_COLABORADOR.NUMCAD,
Nexti.dbo.FLEX_COLABORADOR.DATADMISSAO AS DATALT,
SPF010.PF_TURNODE AS ESCALA,
CAST(SPF010.PF_SEQUEDE AS INT) AS TURMA,
0 AS TIPO,
0 AS SITUACAO,
'' AS OBSERVACAO,
0 AS ID,
Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO AS IDEXTERNO,
'A' AS ORIGEM 
FROM TOTVS_12.dbo.SPF010
JOIN TOTVS_12.dbo.SRA010
    ON SRA010.RA_MAT = SPF010.PF_MAT
    AND SRA010.RA_FILIAL = SPF010.PF_FILIAL
JOIN Nexti.dbo.FLEX_COLABORADOR
    ON Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO = SRA010.R_E_C_N_O_ 
    AND Nexti.dbo.FLEX_COLABORADOR.ID > 0
JOIN Nexti.dbo.FLEX_ESCALA
    ON(
        Nexti.dbo.FLEX_ESCALA.CODESC = SPF010.PF_TURNODE collate database_default
        AND Nexti.dbo.FLEX_ESCALA.ID > 0
    )
WHERE SPF010.PF_DATA = (
    SELECT MIN(SPF.PF_DATA) FROM TOTVS_12.dbo.SPF010 SPF
    WHERE SPF.PF_MAT = SPF010.PF_MAT
    AND SPF.PF_FILIAL = SPF010.PF_FILIAL
    AND SPF.D_E_L_E_T_ = ''
)
AND NOT EXISTS (
    SELECT * FROM Nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS
    WHERE Nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.IDEXTERNO = Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO
    AND Nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.DATALT = Nexti.dbo.FLEX_COLABORADOR.DATADMISSAO
)
AND TOTVS_12.dbo.SPF010.D_E_L_E_T_ = ''
