INSERT INTO Nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS
SELECT DISTINCT
Nexti.dbo.FLEX_COLABORADOR.NUMEMP,
Nexti.dbo.FLEX_COLABORADOR.CODFIL,
Nexti.dbo.FLEX_COLABORADOR.TIPCOL,
Nexti.dbo.FLEX_COLABORADOR.NUMCAD,
SPF010.PF_DATA AS DATALT,
SPF010.PF_TURNOPA AS ESCALA,
CAST(SPF010.PF_SEQUEPA AS INT) AS TURMA,
0 AS TIPO,
0 AS SITUACAO,
'' AS OBSERVACAO,
0 AS ID,
Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO AS IDEXTERNO,
'H' AS ORIGEM
FROM TOTVS_12.dbo.SPF010
JOIN TOTVS_12.dbo.SRA010
    ON SRA010.RA_MAT = SPF010.PF_MAT
    AND SRA010.RA_FILIAL = SPF010.PF_FILIAL
JOIN Nexti.dbo.FLEX_COLABORADOR
    ON Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO = SRA010.R_E_C_N_O_ 
    AND Nexti.dbo.FLEX_COLABORADOR.ID > 0
JOIN Nexti.dbo.FLEX_ESCALA
    ON(
        Nexti.dbo.FLEX_ESCALA.CODESC = SPF010.PF_TURNOPA collate database_default
        AND Nexti.dbo.FLEX_ESCALA.ID > 0
    )
WHERE NOT EXISTS (
    SELECT * FROM Nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS
    WHERE Nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.IDEXTERNO = Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO
    AND Nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.DATALT = SPF010.PF_DATA
    AND Nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.TURMA = CAST(SPF010.PF_SEQUEPA AS INT)
    AND Nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.ESCALA = SPF010.PF_TURNOPA collate database_default
)
AND TOTVS_12.dbo.SPF010.D_E_L_E_T_ = ''
AND SPF010.PF_DATA >= Nexti.dbo.FLEX_COLABORADOR.DATADMISSAO collate database_default