INSERT INTO nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS
SELECT DISTINCT
nexti.dbo.FLEX_COLABORADOR.NUMEMP,
nexti.dbo.FLEX_COLABORADOR.CODFIL,
nexti.dbo.FLEX_COLABORADOR.TIPCOL,
nexti.dbo.FLEX_COLABORADOR.NUMCAD,
SPF010.PF_DATA AS DATALT,
SPF010.PF_TURNOPA AS ESCALA,
CAST(SPF010.PF_SEQUEPA AS INT) AS TURMA,
0 AS TIPO,
0 AS SITUACAO,
'' AS OBSERVACAO,
0 AS ID,
nexti.dbo.FLEX_COLABORADOR.IDEXTERNO AS IDEXTERNO,
'H' AS ORIGEM
FROM ALIANCA.dbo.SPF010
JOIN ALIANCA.dbo.SRA010
    ON SRA010.RA_MAT = SPF010.PF_MAT
    AND SRA010.RA_FILIAL = SPF010.PF_FILIAL
JOIN nexti.dbo.FLEX_COLABORADOR
    ON nexti.dbo.FLEX_COLABORADOR.IDEXTERNO = SRA010.R_E_C_N_O_ 
    AND nexti.dbo.FLEX_COLABORADOR.ID > 0
JOIN nexti.dbo.FLEX_ESCALA
    ON(
        nexti.dbo.FLEX_ESCALA.CODESC = SPF010.PF_TURNOPA collate database_default
        AND nexti.dbo.FLEX_ESCALA.ID > 0
    )
WHERE NOT EXISTS (
    SELECT * FROM nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS
    WHERE nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.IDEXTERNO = nexti.dbo.FLEX_COLABORADOR.IDEXTERNO
    AND nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.DATALT = SPF010.PF_DATA
    AND nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.TURMA = CAST(SPF010.PF_SEQUEPA AS INT)
    AND nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.ESCALA = SPF010.PF_TURNOPA collate database_default
)
AND ALIANCA.dbo.SPF010.D_E_L_E_T_ = ''
AND SPF010.PF_DATA >= nexti.dbo.FLEX_COLABORADOR.DATADMISSAO collate database_default