INSERT INTO nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS
SELECT DISTINCT
nexti.dbo.FLEX_COLABORADOR.NUMEMP,
nexti.dbo.FLEX_COLABORADOR.CODFIL,
nexti.dbo.FLEX_COLABORADOR.TIPCOL,
nexti.dbo.FLEX_COLABORADOR.NUMCAD,
nexti.dbo.FLEX_COLABORADOR.DATADMISSAO AS DATALT,
SPF010.PF_TURNODE AS ESCALA,
CAST(SPF010.PF_SEQUEDE AS INT) AS TURMA,
0 AS TIPO,
0 AS SITUACAO,
'' AS OBSERVACAO,
0 AS ID,
nexti.dbo.FLEX_COLABORADOR.IDEXTERNO AS IDEXTERNO,
'A' AS ORIGEM 
FROM ALIANCA.dbo.SPF010
JOIN ALIANCA.dbo.SRA010
    ON SRA010.RA_MAT = SPF010.PF_MAT
    AND SRA010.RA_FILIAL = SPF010.PF_FILIAL
JOIN nexti.dbo.FLEX_COLABORADOR
    ON nexti.dbo.FLEX_COLABORADOR.IDEXTERNO = SRA010.R_E_C_N_O_ 
    AND nexti.dbo.FLEX_COLABORADOR.ID > 0
JOIN nexti.dbo.FLEX_ESCALA
    ON(
        nexti.dbo.FLEX_ESCALA.CODESC = SPF010.PF_TURNODE collate database_default
        AND nexti.dbo.FLEX_ESCALA.ID > 0
    )
WHERE SPF010.PF_DATA = (
    SELECT MIN(SPF.PF_DATA) FROM ALIANCA.dbo.SPF010 SPF
    WHERE SPF.PF_MAT = SPF010.PF_MAT
    AND SPF.PF_FILIAL = SPF010.PF_FILIAL
    AND SPF.D_E_L_E_T_ = ''
)
AND NOT EXISTS (
    SELECT * FROM nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS
    WHERE nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.IDEXTERNO = nexti.dbo.FLEX_COLABORADOR.IDEXTERNO
    AND nexti.dbo.FLEX_TROCA_ESCALA_PROTHEUS.DATALT = nexti.dbo.FLEX_COLABORADOR.DATADMISSAO
)
AND ALIANCA.dbo.SPF010.D_E_L_E_T_ = ''
