DELETE FROM nexti.dbo.FLEX_AUSENCIAS_PROTHEUS
WHERE nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.TIPO = 0
AND nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.SITUACAO IN(0,2)
AND nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.ABSENCESITUATIONEXTERNALID NOT IN('999', '99999')
AND NOT EXISTS(
	SELECT * FROM ALIANCA.dbo.SR8010
	JOIN ALIANCA.dbo.SRA010 SRA010
	    ON SRA010.RA_FILIAL = SR8010.R8_FILIAL
	    AND SRA010.RA_MAT = SR8010.R8_MAT
	JOIN nexti.dbo.FLEX_COLABORADOR 
		ON nexti.dbo.FLEX_COLABORADOR.IDEXTERNO = SRA010.R_E_C_N_O_
	    AND nexti.dbo.FLEX_COLABORADOR.ID > 0
    JOIN nexti.dbo.FLEX_SITUACAO
		ON nexti.dbo.FLEX_SITUACAO.CODSIT = SR8010.R8_TIPOAFA collate database_default
		AND nexti.dbo.FLEX_SITUACAO.ID > 0
	WHERE nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.PERSONEXTERNALID = nexti.dbo.FLEX_COLABORADOR.IDEXTERNO
	AND nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.STARTDATETIME = CONVERT(DATETIME, SR8010.R8_DATAINI, 120)
	AND nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.FINISHDATETIME = CONVERT(DATETIME, SR8010.R8_DATAFIM, 120)
	AND RTRIM(nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.ABSENCESITUATIONEXTERNALID) = RTRIM(nexti.dbo.FLEX_SITUACAO.IDEXTERNO)
	AND ALIANCA.dbo.SR8010.D_E_L_E_T_ = ''
)