UPDATE Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS
SET Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.TIPO = 3,
Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.SITUACAO = 0
WHERE Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.ID > 0
AND NOT EXISTS(
	SELECT * FROM TOTVS_12.dbo.SR8010
	JOIN TOTVS_12.dbo.SRA010 SRA010
	    ON SRA010.RA_FILIAL = SR8010.R8_FILIAL
	    AND SRA010.RA_MAT = SR8010.R8_MAT
	JOIN Nexti.dbo.FLEX_COLABORADOR
		ON Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO = SRA010.R_E_C_N_O_ 
	    AND Nexti.dbo.FLEX_COLABORADOR.ID > 0
    JOIN Nexti.dbo.FLEX_SITUACAO
		ON Nexti.dbo.FLEX_SITUACAO.CODSIT = SR8010.R8_TIPOAFA collate database_default
		AND Nexti.dbo.FLEX_SITUACAO.ID > 0
	WHERE Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.PERSONEXTERNALID = Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO 
	AND Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.STARTDATETIME = CONVERT(DATETIME, SR8010.R8_DATAINI, 120)
	AND Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.FINISHDATETIME = CONVERT(DATETIME, SR8010.R8_DATAFIM, 120)
	AND RTRIM(Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.ABSENCESITUATIONEXTERNALID) = RTRIM(Nexti.dbo.FLEX_SITUACAO.IDEXTERNO)
	AND TOTVS_12.dbo.SR8010.D_E_L_E_T_ = ''
)
AND Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.ABSENCESITUATIONEXTERNALID NOT IN('999', '99999')