UPDATE nexti.dbo.FLEX_AUSENCIAS_PROTHEUS
SET nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.TIPO = 3,
nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.SITUACAO = 0
WHERE nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.ABSENCESITUATIONEXTERNALID = '999'
AND nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.SITUACAO = 1
AND nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.TIPO = 0
AND NOT EXISTS(
	SELECT * FROM nexti.dbo.FLEX_COLABORADOR
	WHERE nexti.dbo.FLEX_COLABORADOR.IDEXTERNO = nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.PERSONEXTERNALID
	AND nexti.dbo.FLEX_COLABORADOR.DATADEMISSAO = nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.STARTDATETIME
)
