UPDATE Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS
SET Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.TIPO = 3,
Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.SITUACAO = 0
WHERE Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.ABSENCESITUATIONEXTERNALID = '999'
AND Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.SITUACAO = 1
AND Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.TIPO = 0
AND NOT EXISTS(
	SELECT * FROM Nexti.dbo.FLEX_COLABORADOR
	WHERE Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO = Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.PERSONEXTERNALID
	AND Nexti.dbo.FLEX_COLABORADOR.DATADEMISSAO = Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.STARTDATETIME
)
