INSERT INTO nexti.dbo.FLEX_AUSENCIAS_PROTHEUS
SELECT 
nexti.dbo.FLEX_COLABORADOR.NUMEMP,
nexti.dbo.FLEX_COLABORADOR.CODFIL,
nexti.dbo.FLEX_COLABORADOR.TIPCOL,
nexti.dbo.FLEX_COLABORADOR.NUMCAD,
'999' AS ABSENCESITUATIONEXTERNALID,
19454 AS ABSENCESITUATIONID,
CONVERT(DATETIME,'1900-01-01', 120) AS FINISHDATETIME,
0 AS FINISHMINUTE,
CONVERT(DATETIME, LTRIM(RTRIM(nexti.dbo.FLEX_COLABORADOR.DATADEMISSAO)), 120) AS STARTDATETIME,
0 AS STARTMINUTE,
nexti.dbo.FLEX_COLABORADOR.IDEXTERNO AS PERSONEXTERNALID,
nexti.dbo.FLEX_COLABORADOR.ID AS PERSONID,
0 AS TIPO,
0 AS SITUACAO,
0 AS OBSERVACAO,
0 AS ID,
nexti.dbo.FLEX_COLABORADOR.IDEXTERNO AS IDEXTERNO
FROM nexti.dbo.FLEX_COLABORADOR
WHERE nexti.dbo.FLEX_COLABORADOR.ID > 0
AND (
	LTRIM(RTRIM(nexti.dbo.FLEX_COLABORADOR.DATADEMISSAO)) <> ''
)	
AND NOT EXISTS(
	SELECT * FROM nexti.dbo.FLEX_AUSENCIAS_PROTHEUS
	WHERE nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.IDEXTERNO = nexti.dbo.FLEX_COLABORADOR.IDEXTERNO 
	AND nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.STARTDATETIME =CONVERT(DATETIME, LTRIM(RTRIM(nexti.dbo.FLEX_COLABORADOR.DATADEMISSAO)), 120)
	AND nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.FINISHDATETIME = CONVERT(DATETIME,'1900-01-01', 120)
	AND RTRIM(nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.ABSENCESITUATIONEXTERNALID) = '999'
)