INSERT INTO nexti.dbo.FLEX_AUSENCIAS_PROTHEUS
SELECT DISTINCT
nexti.dbo.FLEX_COLABORADOR.NUMEMP,
nexti.dbo.FLEX_COLABORADOR.CODFIL,
nexti.dbo.FLEX_COLABORADOR.TIPCOL,
nexti.dbo.FLEX_COLABORADOR.NUMCAD,
nexti.dbo.FLEX_SITUACAO.IDEXTERNO AS ABSENCESITUATIONEXTERNALID,
nexti.dbo.FLEX_SITUACAO.ID AS ABSENCESITUATIONID,
CONVERT(DATETIME, SR8010.R8_DATAFIM, 120) AS FINISHDATETIME,
0 AS FINISHMINUTE,
CONVERT(DATETIME, SR8010.R8_DATAINI, 120) AS STARTDATETIME,
0 AS STARTMINUTE,
nexti.dbo.FLEX_COLABORADOR.IDEXTERNO AS PERSONEXTERNALID,
nexti.dbo.FLEX_COLABORADOR.ID AS PERSONID,
0 AS TIPO,
0 AS SITUACAO,
0 AS OBSERVACAO,
0 AS ID,
nexti.dbo.FLEX_COLABORADOR.IDEXTERNO AS IDEXTERNO
FROM ALIANCA.dbo.SR8010
JOIN ALIANCA.dbo.SRA010 SRA010
    ON SRA010.RA_FILIAL = SR8010.R8_FILIAL
    AND SRA010.RA_MAT = SR8010.R8_MAT
    AND SRA010.D_E_L_E_T_ = ''
JOIN nexti.dbo.FLEX_COLABORADOR
	ON nexti.dbo.FLEX_COLABORADOR.IDEXTERNO = SRA010.R_E_C_N_O_
    AND nexti.dbo.FLEX_COLABORADOR.ID > 0
JOIN nexti.dbo.FLEX_EMPRESA
	ON nexti.dbo.FLEX_EMPRESA.NUMEMP = nexti.dbo.FLEX_COLABORADOR.NUMEMP
JOIN nexti.dbo.FLEX_SITUACAO
	ON nexti.dbo.FLEX_SITUACAO.CODSIT = SR8010.R8_TIPOAFA collate database_default
	AND nexti.dbo.FLEX_SITUACAO.ID > 0
WHERE SR8010.D_E_L_E_T_ = ''
AND NOT EXISTS(
	SELECT * FROM nexti.dbo.FLEX_AUSENCIAS_PROTHEUS
	WHERE nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.NUMEMP = nexti.dbo.FLEX_COLABORADOR.NUMEMP 
	AND nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.CODFIL = nexti.dbo.FLEX_COLABORADOR.CODFIL 
	AND nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.TIPCOL = nexti.dbo.FLEX_COLABORADOR.TIPCOL 
	AND nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.NUMCAD = nexti.dbo.FLEX_COLABORADOR.NUMCAD 
	AND nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.IDEXTERNO = nexti.dbo.FLEX_COLABORADOR.IDEXTERNO 
	AND nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.STARTDATETIME = CONVERT(DATETIME, SR8010.R8_DATAINI, 120)
	AND nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.FINISHDATETIME = CONVERT(DATETIME, SR8010.R8_DATAFIM, 120)
	AND RTRIM(nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.ABSENCESITUATIONEXTERNALID) = RTRIM(nexti.dbo.FLEX_SITUACAO.IDEXTERNO)
)