INSERT INTO Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS
SELECT 
Nexti.dbo.FLEX_COLABORADOR.NUMEMP,
Nexti.dbo.FLEX_COLABORADOR.CODFIL,
Nexti.dbo.FLEX_COLABORADOR.TIPCOL,
Nexti.dbo.FLEX_COLABORADOR.NUMCAD,
'999' AS ABSENCESITUATIONEXTERNALID,
19454 AS ABSENCESITUATIONID,
CONVERT(DATETIME,'1900-01-01', 120) AS FINISHDATETIME,
0 AS FINISHMINUTE,
CONVERT(DATETIME, LTRIM(RTRIM(Nexti.dbo.FLEX_COLABORADOR.DATADEMISSAO)), 120) AS STARTDATETIME,
0 AS STARTMINUTE,
Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO AS PERSONEXTERNALID,
Nexti.dbo.FLEX_COLABORADOR.ID AS PERSONID,
0 AS TIPO,
0 AS SITUACAO,
0 AS OBSERVACAO,
0 AS ID,
Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO AS IDEXTERNO
FROM Nexti.dbo.FLEX_COLABORADOR
WHERE Nexti.dbo.FLEX_COLABORADOR.ID > 0
AND (
	LTRIM(RTRIM(Nexti.dbo.FLEX_COLABORADOR.DATADEMISSAO)) <> ''
)	
AND NOT EXISTS(
	SELECT * FROM Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS
	WHERE Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.IDEXTERNO = Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO 
	AND Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.STARTDATETIME =CONVERT(DATETIME, LTRIM(RTRIM(Nexti.dbo.FLEX_COLABORADOR.DATADEMISSAO)), 120)
	AND Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.FINISHDATETIME = CONVERT(DATETIME,'1900-01-01', 120)
	AND RTRIM(Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.ABSENCESITUATIONEXTERNALID) = '999'
)