INSERT INTO Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS
SELECT DISTINCT
Nexti.dbo.FLEX_COLABORADOR.NUMEMP,
Nexti.dbo.FLEX_COLABORADOR.CODFIL,
Nexti.dbo.FLEX_COLABORADOR.TIPCOL,
Nexti.dbo.FLEX_COLABORADOR.NUMCAD,
Nexti.dbo.FLEX_SITUACAO.IDEXTERNO AS ABSENCESITUATIONEXTERNALID,
Nexti.dbo.FLEX_SITUACAO.ID AS ABSENCESITUATIONID,
CONVERT(DATETIME, SR8010.R8_DATAFIM, 120) AS FINISHDATETIME,
0 AS FINISHMINUTE,
CONVERT(DATETIME, SR8010.R8_DATAINI, 120) AS STARTDATETIME,
0 AS STARTMINUTE,
Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO AS PERSONEXTERNALID,
Nexti.dbo.FLEX_COLABORADOR.ID AS PERSONID,
0 AS TIPO,
0 AS SITUACAO,
0 AS OBSERVACAO,
0 AS ID,
Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO AS IDEXTERNO
FROM TOTVS_12.dbo.SR8010
JOIN TOTVS_12.dbo.SRA010 SRA010
    ON SRA010.RA_FILIAL = SR8010.R8_FILIAL
    AND SRA010.RA_MAT = SR8010.R8_MAT
    AND SRA010.D_E_L_E_T_ = ''
JOIN Nexti.dbo.FLEX_COLABORADOR
	ON Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO = SRA010.R_E_C_N_O_
    AND Nexti.dbo.FLEX_COLABORADOR.ID > 0
JOIN Nexti.dbo.FLEX_EMPRESA
	ON Nexti.dbo.FLEX_EMPRESA.NUMEMP = Nexti.dbo.FLEX_COLABORADOR.NUMEMP
JOIN Nexti.dbo.FLEX_SITUACAO
	ON Nexti.dbo.FLEX_SITUACAO.CODSIT = SR8010.R8_TIPOAFA collate database_default
	AND Nexti.dbo.FLEX_SITUACAO.ID > 0
WHERE SR8010.D_E_L_E_T_ = ''
AND NOT EXISTS(
	SELECT * FROM Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS
	WHERE Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.NUMEMP = Nexti.dbo.FLEX_COLABORADOR.NUMEMP 
	AND Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.CODFIL = Nexti.dbo.FLEX_COLABORADOR.CODFIL 
	AND Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.TIPCOL = Nexti.dbo.FLEX_COLABORADOR.TIPCOL 
	AND Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.NUMCAD = Nexti.dbo.FLEX_COLABORADOR.NUMCAD 
	AND Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.IDEXTERNO = Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO 
	AND Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.STARTDATETIME = CONVERT(DATETIME, SR8010.R8_DATAINI, 120)
	AND Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.FINISHDATETIME = CONVERT(DATETIME, SR8010.R8_DATAFIM, 120)
	AND RTRIM(Nexti.dbo.FLEX_AUSENCIAS_PROTHEUS.ABSENCESITUATIONEXTERNALID) = RTRIM(Nexti.dbo.FLEX_SITUACAO.IDEXTERNO)
)