UPDATE Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS
SET Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.TIPO = 3,
Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.SITUACAO = 0
WHERE Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.ID > 0
AND EXISTS(
	SELECT * FROM Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS NTP
	WHERE NTP.IDEXTERNO = Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.IDEXTERNO
	AND NTP.INIATU = Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.INIATU
	AND NTP.SITUACAO IN(0,2)
	AND NTP.TIPO = 0
	AND NTP.TIPO_TROCA = 'P'
)
AND Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.TIPO_TROCA = 'A'