UPDATE Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS
SET Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.TIPO = 3,
Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.SITUACAO = 0
WHERE  Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.TIPO_TROCA = 'A'
AND NOT EXISTS(
	SELECT * FROM  Nexti.dbo.FLEX_COLABORADOR
	WHERE  Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO =  Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.IDEXTERNO
	AND  Nexti.dbo.FLEX_COLABORADOR.DATADMISSAO =  Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.INIATU
)
AND Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.ID > 0