UPDATE nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS
SET nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.TIPO = 3,
nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.SITUACAO = 0
WHERE  nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.TIPO_TROCA = 'A'
AND NOT EXISTS(
	SELECT * FROM  nexti.dbo.FLEX_COLABORADOR
	WHERE  nexti.dbo.FLEX_COLABORADOR.IDEXTERNO =  nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.IDEXTERNO
	AND  nexti.dbo.FLEX_COLABORADOR.DATADMISSAO =  nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.INIATU
)
AND nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.ID > 0