UPDATE nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS
SET nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.TIPO = 3,
nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.SITUACAO = 0
WHERE nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.ID > 0
AND EXISTS(
	SELECT * FROM nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS NTP
	WHERE NTP.IDEXTERNO = nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.IDEXTERNO
	AND NTP.INIATU = nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.INIATU
	AND NTP.SITUACAO IN(0,2)
	AND NTP.TIPO = 0
	AND NTP.TIPO_TROCA = 'P'
)
AND nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.TIPO_TROCA = 'A'