UPDATE nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS
SET nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.TIPO = 3,
nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.SITUACAO = 0
WHERE nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.TIPO_TROCA = 'A'
AND nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.SITUACAO = 1
AND nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.TIPO = 0
AND nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.NUMEMP = 1
AND EXISTS(
	SELECT * FROM ALIANCA.dbo.SRA010
	WHERE SRA010.R_E_C_N_O_ = nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.IDEXTERNO
	AND SRA010.RA_CC <> nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.CODCCU collate database_default
	AND SRA010.D_E_L_E_T_ = ''
)
AND NOT EXISTS(
	SELECT * FROM nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS NTP
	WHERE NTP.IDEXTERNO = nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.IDEXTERNO
	AND NTP.TIPO_TROCA <> 'A'
)