UPDATE Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS
SET Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.TIPO = 3,
Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.SITUACAO = 0
WHERE Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.TIPO_TROCA = 'A'
AND Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.SITUACAO = 1
AND Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.TIPO = 0
AND Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.NUMEMP = 1
AND EXISTS(
	SELECT * FROM TOTVS_12.dbo.SRA010
	WHERE SRA010.R_E_C_N_O_ = Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.IDEXTERNO
	AND SRA010.RA_CC <> Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.CODCCU collate database_default
	AND SRA010.D_E_L_E_T_ = ''
)
AND NOT EXISTS(
	SELECT * FROM Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS NTP
	WHERE NTP.IDEXTERNO = Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.IDEXTERNO
	AND NTP.TIPO_TROCA <> 'A'
)