INSERT INTO nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS
SELECT 
0 AS ID,
nexti.dbo.FLEX_COLABORADOR.IDEXTERNO,
nexti.dbo.FLEX_COLABORADOR.NUMEMP,
SRE010.RE_FILIALP AS CODFIL,
nexti.dbo.FLEX_COLABORADOR.TIPCOL,
nexti.dbo.FLEX_COLABORADOR.NUMCAD,
SRE010.RE_DATA AS INIATU,
nexti.dbo.FLEX_POSTO.ESTPOS,
nexti.dbo.FLEX_POSTO.POSTRA,
nexti.dbo.FLEX_POSTO.CODCCU,
0 AS TIPO,
0 AS SITUACAO,
'' AS OBSERVACAO,
'P' AS TIPO_TROCA 
FROM ALIANCA.dbo.SRE010
JOIN ALIANCA.dbo.SRA010
	ON SRA010.RA_FILIAL = SRE010.RE_FILIALP
	AND SRA010.RA_MAT = SRE010.RE_MATP
JOIN nexti.dbo.FLEX_COLABORADOR
	ON FLEX_COLABORADOR.IDEXTERNO = SRA010.R_E_C_N_O_
	AND nexti.dbo.FLEX_COLABORADOR.ID > 0
JOIN nexti.dbo.FLEX_POSTO
    ON nexti.dbo.FLEX_POSTO.CODCCU = SRE010.RE_CCP collate database_default
    AND nexti.dbo.FLEX_POSTO.ID > 0
	AND nexti.dbo.FLEX_POSTO.CODFIL = SUBSTRING(SRE010.RE_FILIALP,1,2) collate database_default
	AND nexti.dbo.FLEX_POSTO.CTT_BLOQ <> 1
WHERE SRE010.D_E_L_E_T_ = '' 
AND NOT EXISTS(
	SELECT * FROM nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS
	WHERE nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.IDEXTERNO = nexti.dbo.FLEX_COLABORADOR.IDEXTERNO
	AND nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.INIATU = SRE010.RE_DATA 
	AND nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.CODCCU = nexti.dbo.FLEX_POSTO.CODCCU
) 
AND SRE010.RE_DATA >= nexti.dbo.FLEX_COLABORADOR.DATADMISSAO collate database_default
AND nexti.dbo.FLEX_POSTO.POSTRA NOT IN('2003', '5153', '5187')