INSERT INTO Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS
SELECT 
0 AS ID,
Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO,
Nexti.dbo.FLEX_COLABORADOR.NUMEMP,
SRE010.RE_FILIALP AS CODFIL,
Nexti.dbo.FLEX_COLABORADOR.TIPCOL,
Nexti.dbo.FLEX_COLABORADOR.NUMCAD,
SRE010.RE_DATA AS INIATU,
Nexti.dbo.FLEX_POSTO.ESTPOS,
Nexti.dbo.FLEX_POSTO.POSTRA,
Nexti.dbo.FLEX_POSTO.CODCCU,
0 AS TIPO,
0 AS SITUACAO,
'' AS OBSERVACAO,
'P' AS TIPO_TROCA 
FROM TOTVS_12.dbo.SRE010
JOIN TOTVS_12.dbo.SRA010
	ON SRA010.RA_FILIAL = SRE010.RE_FILIALP
	AND SRA010.RA_MAT = SRE010.RE_MATP
JOIN Nexti.dbo.FLEX_COLABORADOR
	ON FLEX_COLABORADOR.IDEXTERNO = SRA010.R_E_C_N_O_
	AND Nexti.dbo.FLEX_COLABORADOR.ID > 0
JOIN Nexti.dbo.FLEX_POSTO
    ON Nexti.dbo.FLEX_POSTO.CODCCU = SRE010.RE_CCP collate database_default
    AND Nexti.dbo.FLEX_POSTO.ID > 0
	AND Nexti.dbo.FLEX_POSTO.NUMEMP = SUBSTRING(SRE010.RE_FILIALP,1,2) collate database_default
	AND Nexti.dbo.FLEX_POSTO.CTT_BLOQ <> 1
WHERE SRE010.D_E_L_E_T_ = '' 
AND NOT EXISTS(
	SELECT * FROM Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS
	WHERE Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.IDEXTERNO = Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO
	AND Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.INIATU = SRE010.RE_DATA 
	AND Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS.CODCCU = Nexti.dbo.FLEX_POSTO.CODCCU
) 
AND SRE010.RE_DATA >= Nexti.dbo.FLEX_COLABORADOR.DATADMISSAO collate database_default