INSERT INTO Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS
SELECT DISTINCT
	0 AS ID,
	FLEX_COLABORADOR.IDEXTERNO,
	FLEX_COLABORADOR.NUMEMP,
	FLEX_COLABORADOR.CODFIL,
	FLEX_COLABORADOR.TIPCOL,
	FLEX_COLABORADOR.NUMCAD,
	FLEX_COLABORADOR.DATADMISSAO AS INIATU,
	FLEX_POSTO.ESTPOS,
	FLEX_POSTO.POSTRA,
	FLEX_POSTO.CODCCU,
	0 AS TIPO,
	0 AS SITUACAO,
	'' AS OBSERVACAO,
	'A' AS TIPO_TROCA
FROM Nexti.dbo.FLEX_COLABORADOR
JOIN TOTVS_12.dbo.SRA010
	ON(
		FLEX_COLABORADOR.R_E_C_N_O_ = SRA010.R_E_C_N_O_
		AND FLEX_COLABORADOR.ID > 0
	)
JOIN Nexti.dbo.FLEX_POSTO
	ON(
		FLEX_POSTO.CODCCU = SRA010.RA_CC collate database_default
		AND FLEX_POSTO.NUMEMP = FLEX_COLABORADOR.NUMEMP
	    AND FLEX_POSTO.ID > 0
	)
WHERE NOT EXISTS(
	SELECT
		1
	FROM Nexti.dbo.FLEX_TROCA_POSTO_PROTHEUS
	WHERE FLEX_TROCA_POSTO_PROTHEUS.IDEXTERNO = FLEX_COLABORADOR.IDEXTERNO
	AND FLEX_TROCA_POSTO_PROTHEUS.INIATU = FLEX_COLABORADOR.DATADMISSAO
	AND FLEX_TROCA_POSTO_PROTHEUS.NUMCAD = FLEX_COLABORADOR.NUMCAD
)
AND FLEX_COLABORADOR.ID > 0
GROUP BY FLEX_COLABORADOR.IDEXTERNO,
	FLEX_COLABORADOR.NUMEMP,
	FLEX_COLABORADOR.CODFIL,
	FLEX_COLABORADOR.TIPCOL,
	FLEX_COLABORADOR.NUMCAD,
	FLEX_COLABORADOR.DATADMISSAO,
	FLEX_POSTO.ESTPOS,
	FLEX_POSTO.POSTRA,
	FLEX_POSTO.CODCCU