INSERT INTO nexti.dbo.FLEX_CONTRA_CHEQUE_COMPETENCIA
SELECT 
*
FROM (
	SELECT
	nexti.dbo.FLEX_EMPRESA.NUMEMP,
	nexti.dbo.FLEX_EMPRESA.CODFIL,
	(CAST(nexti.dbo.FLEX_EMPRESA.IDEXTERNO collate database_default AS VARCHAR(50)) + '-' +  CAST(SRD010.RD_PERIODO AS VARCHAR(50))) AS IDEXTERNO,
	0 AS ID,
	( SUBSTRING(SRD010.RD_PERIODO,5,2) + '/' +  SUBSTRING(SRD010.RD_PERIODO,0,5) + '-FOL01') AS NAME,
	( SUBSTRING(SRD010.RD_PERIODO,0,5) + '-' + SUBSTRING(SRD010.RD_PERIODO,5,2) + '-' + '01') AS PAYCHECKPERIODDATE,
	0 AS TIPO,
	0 AS SITUACAO,
	'' AS OBSERVACAO,
	CASE 
		WHEN MONTH(SRD010.RD_DATPGT) < MONTH(GETDATE()) 
			AND YEAR(SRD010.RD_DATPGT) <= YEAR(GETDATE()) 
		THEN DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 4)
		ELSE SRD010.RD_DATPGT
	END AS DATPAG
	FROM ALIANCA.dbo.SRD010
	JOIN nexti.dbo.FLEX_EMPRESA
		ON nexti.dbo.FLEX_EMPRESA.CODFIL = LEFT(SRD010.RD_FILIAL,2) collate database_default
	WHERE SRD010.RD_ROTEIR = 'FOL'
	AND SRD010.RD_PROCES = '00001'
	AND SRD010.RD_PERIODO >= '202501'
	AND SRD010.RD_PD IN ('101')
	AND (SRD010.D_E_L_E_T_ = '0' OR SRD010.D_E_L_E_T_ = '')
) GERAL
WHERE NOT EXISTS(
	SELECT * FROM nexti.dbo.FLEX_CONTRA_CHEQUE_COMPETENCIA
	WHERE nexti.dbo.FLEX_CONTRA_CHEQUE_COMPETENCIA.IDEXTERNO = GERAL.IDEXTERNO collate database_default
)
AND DATEADD(DAY, -1, GERAL.DATPAG) <= GETDATE()
GROUP BY 
GERAL.NUMEMP,
GERAL.CODFIL,
GERAL.IDEXTERNO,
GERAL.ID,
GERAL.NAME,
GERAL.PAYCHECKPERIODDATE,
GERAL.TIPO,
GERAL.SITUACAO,
GERAL.OBSERVACAO,
GERAL.DATPAG