INSERT INTO Nexti.dbo.FLEX_CONTRA_CHEQUE_EVENTOS
SELECT DISTINCT
SRD010.RD_VALOR AS cost,
SRV010.RV_DESC AS description,
SRD010.RD_PD AS id,
SRV010.RV_TIPOCOD AS paycheckRecordTypeId,
SRD010.RD_HORAS AS reference,
(CAST(Nexti.dbo.FLEX_EMPRESA.IDEXTERNO collate database_default AS VARCHAR(50)) + '-' +
 Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO + '-' +
 CAST(SRD010.RD_PERIODO AS VARCHAR(50)))  AS ID_CONTRA_CHEQUE,
0 AS TIPO,
0 AS SITUACAO,
0 AS OBSERVACAO,
NULL AS paycheckPeriodId,
NULL AS BASE_INSS,
NULL AS BASE_FGTS,
NULL AS BASE_IRRF
FROM TOTVS_12.dbo.SRD010
JOIN TOTVS_12.dbo.SRV010
    ON RV_COD = RD_PD
    AND RV_FILIAL = LEFT(SRD010.RD_FILIAL,2)
JOIN TOTVS_12.dbo.SRA010
    ON SRA010.RA_MAT = SRD010.RD_MAT
    AND SRA010.RA_FILIAL = SRD010.RD_FILIAL
JOIN Nexti.dbo.FLEX_EMPRESA
    ON Nexti.dbo.FLEX_EMPRESA.NUMEMP = LEFT(SRD010.RD_FILIAL,2) collate database_default
JOIN Nexti.dbo.FLEX_COLABORADOR
    ON Nexti.dbo.FLEX_COLABORADOR.CPF = LTRIM(RTRIM(SRA010.RA_CIC)) collate database_default
    AND Nexti.dbo.FLEX_COLABORADOR.CODFIL = SRD010.RD_FILIAL collate database_default
    AND (Nexti.dbo.FLEX_COLABORADOR.DATADEMISSAO = '' OR Nexti.dbo.FLEX_COLABORADOR.DATADEMISSAO IS NULL)
WHERE RD_ROTEIR = 'FOL'
AND RD_PROCES = '00001'
AND ( SRD010.R_E_C_D_E_L_ = 0 OR SRD010.R_E_C_D_E_L_ = '')
AND RV_TIPOCOD IN('1','2')
AND NOT EXISTS(
    SELECT * FROM Nexti.dbo.FLEX_CONTRA_CHEQUE_EVENTOS
    WHERE Nexti.dbo.FLEX_CONTRA_CHEQUE_EVENTOS.id = SRD010.RD_PD collate database_default
    AND Nexti.dbo.FLEX_CONTRA_CHEQUE_EVENTOS.ID_CONTRA_CHEQUE = (CAST(Nexti.dbo.FLEX_EMPRESA.IDEXTERNO collate database_default AS VARCHAR(50)) + '-' +
 Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO + '-' +
 CAST(SRD010.RD_PERIODO AS VARCHAR(50)))   collate database_default
)
AND EXISTS(
    SELECT * FROM Nexti.dbo.FLEX_CONTRA_CHEQUE
    WHERE Nexti.dbo.FLEX_CONTRA_CHEQUE.IDEXTERNO = (CAST(Nexti.dbo.FLEX_EMPRESA.IDEXTERNO collate database_default AS VARCHAR(50)) + '-' +
     Nexti.dbo.FLEX_COLABORADOR.IDEXTERNO + '-' +
     CAST(SRD010.RD_PERIODO AS VARCHAR(50)))  collate database_default
)